repos:
- repo: https://github.com/errata-ai/vale
  rev: v3.9.3
  hooks:
  - id: vale
    name: vale-sync
    pass_filenames: false
    args: [sync]
    stages: [pre-commit]
  - id: vale
    verbose: true
    log_file: commit-msg
        #    args: ['--output=.vale_template']
    stages: [pre-commit]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0  # Use the ref you want to point at
  hooks:
    - id: trailing-whitespace
      stages: [pre-commit]
    - id: check-yaml
      stages: [pre-commit]
      args: [--allow-multiple-documents]
    - id: forbid-submodules
      stages: [pre-commit]
    - id: no-commit-to-branch
      stages: [pre-commit]
    - id: end-of-file-fixer
      stages: [pre-commit]
    - id: mixed-line-ending
      stages: [pre-commit]
    - id: check-merge-conflict
      stages: [pre-commit]
    - id: check-added-large-files
      stages: [pre-commit]
      args: ['--maxkb=256']
- repo: local
  hooks:
    - id: append-to-commit-message
      name: Append to commit message
      entry: ./.vale_append_to_commit_message.sh
      language: script
      stages: [prepare-commit-msg]
